Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specs/', include('specs.urls')),
    path('api/', include('mainapp.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainapp/api/urls.py
from django.urls import path

from .api_views import (CustomerListAPIView,
                        CategoryAPIView,
                        SmartphoneListAPIView,
                        NotebookListAPIView,
                        NotebookDetailApiView,
                        )
urlpatterns = [
    path('customers/', CustomerListAPIView.as_view(),  name='customers_list'),
    path('catigories/<str:id>', CategoryAPIView.as_view(),  name='catigories_list'),
    path('smartphone/', SmartphoneListAPIView.as_view(),  name='smartphone_list'),
    path('notebook/', NotebookListAPIView.as_view(),  name='notebook_list'),
    path('notebook/<str:id>', NotebookDetailApiView.as_view(),  name='notebook')
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView,
    ProfileView
)

urlpatterns = [
    path('', BaseView.as_view(), name = 'base'),
    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-to-cart/<str:slug>/', DeleteFromCartView.as_view(), name='remove_to_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils import timezone

User = get_user_model()

class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name="Имя категории")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug':self.slug})

    # def get_filds_for_filter_in_template(self):
    #     return ProductFeatures.objects.filter(
    #         category=self,
    #         use_in_filter=True
    #     ).prefetch_related('category').value('feature_key', 'feature_measure', 'feature_name', 'filter_type' )

class Product(models.Model):

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Наимование")
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name="Изображение")
    description = models.TextField(verbose_name="Описание", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug' : self.slug})

# class ProductFeatures(models.Model):
#
#     RADIO = 'radio'
#     CHECKBOX = 'checkbox'
#
#     FILTER_TYPE_CHOICES = (
#         (RADIO, 'радиокнопка'),
#         (CHECKBOX, 'чекбокс'),
#     )
#
#     fature_key = models.CharField(max_length=100, verbose_name="Ключ характеристики")
#     fature_name = models.CharField(max_length=100, verbose_name="Наимование характеристики")
#     category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
#     postfix_for_value = models.CharField(
#         max_length=20,
#         null=True,
#         blank=True,
#         verbose_name="Постфикс для значения",
#         help_text=f'Например для характеристики "Часы работы" '
#                   f'к знанию можно добавить постфикс "часов", и как результат - значения "10 часов" '
#     )
#     use_in_filter = models.BooleanField(
#         default=False,
#         verbose_name='Использовать в фильтрации товаров в шаблоне')
#
#     filter_type = models.CharField(
#         max_length=20,
#         verbose_name="Тип фильтра",
#         default=CHECKBOX,
#         choices=FILTER_TYPE_CHOICES
#     )
#
#     feature_measure = models.CharField(
#         max_length=50,
#         verbose_name='Единица измерения для фильтра',
#         help_text='Единица измерения для конкретного фильтра. Например "Частота процессора (Ghz)".'
#                   'Единицей измерения будет информация в скобках'
#     )
#
#     def __str__(self):
#         return f'Категория - "{self.category.name}" | Характеристика - "{self.fature_name}"'

# class ProductFeatureValidators(models.Model):
#
#     category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
#     feature = models.ForeignKey(ProductFeatures, verbose_name='Характеристика', null=True, blank=True, on_delete=models.CASCADE)
#     feature_value = models.CharField(max_length=255, unique=True, null=True, blank=True, verbose_name='Значение характеристики')
#
#     def __str__(self):
#         if not self.feature:
#             return f'Валидатор категории "{self.category.name}" - характеристика не выбрана '
#         return f'Валидатор категории "{self.category.name} | ' \
#                f'Характеристика - "{self.feature.feature_name}" |' \
#                f'Значение - "{self.feature_value}"'

class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name="Покупатель", on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name="Корзина", on_delete=models.CASCADE)
    product = models.ForeignKey('Product', verbose_name="Товар", on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена")

    def __str__(self):
        return f"Продукт: {self.product.title} (для корзины)"

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)

class Cart(models.Model):

    owner = models.ForeignKey("Customer", null=True, verbose_name="Владелец", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_card")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Общая цена")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    phone = models.CharField(max_length=255, verbose_name="Номер Телефона", null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name="Аддрес", null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return f"Покупатель {self.user.first_name} {self.user.last_name}"

# class Specifications(models.Model):
#
#     content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
#     object_id = models.PositiveIntegerField()
#     name = models.CharField(max_length=255, verbose_name="имя товара для характеристики")
#
#     def __str__(self):
#         return f"характеристики для товара {self.name}"

class Order(models.Model):

    STAUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STAUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен'),
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка'),
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='relaed_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STAUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Коментарий к заказу', null=True, blank=True )
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateTimeField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Order

class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )

class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
            return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']

class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Ваша имя'
        self.fields['last_name'].label = 'Ваша фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(f'Регистрация для домена "{domain}" невозможна')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Данный почтовый адрес уже загистрирован в системе')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли несовпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>shop</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="main.css">
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>
<style>
    body {
    padding-top: 56px;
    }
</style>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}">Shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
                  <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Категории
      </a>
      <div class="dropdown-menu">
          {% for category in categories %}
              <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
          {% endfor %}
      </div>

    </li>
          {% if not request.user.is_authenticated %}
              <li>
                  <a class="navbar-link text-light" href="{% url 'login' %}">Авторизация</a>
              </li>
              <dir>
              <li>
                  <a class="navbar-link text-light" href="{% url 'registration' %}">Регистрация</a>
              </li>
              </dir>
          {% endif %}
          <li class="nav-item">
              {% if request.user.is_authenticated %}<span class="navbar text text-light">Здравствуйте, <span class="badge badge-danger">
              <a style="text-decoration: none; font-size: 14px; color: white"  href="{% url 'profile' %}">{{ request.user.username }}</a>
          </span>| <a href="{% url 'logout' %}" style="color: white; text-decoration: none">Выйти</a></span>
              {% endif %}
          </li>
          </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span> </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        <div class="list-group">
            {% for category in categories %}
                <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
            {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        {% block content %}
            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="card-img-top" src="" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>


        <div class="row">
        {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
               <div style="width: 100%; height: 300px;.card img{ width: 100%;}">
                   <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a></div>
              <div class="card-body">
                <h4 class="card-title">
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} $</h5>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                    <button class="btn btn-danger">Добавить в корзину</button></a>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        <!-- /.row -->
        {% endblock %}

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">+__________+</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% if cart.products.count %}
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Наимование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.product.title }}</th>
      <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
      <td>{{ item.product.price }} $.</td>
      <td>
          <form action="{% url 'change_qty'  slug=item.product.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-primary" value="Изминить кол-во">
          </form>
      </td>
        <td> {{ item.final_price }} $.</td>
    <td>
        <a href="{% url 'remove_to_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
    </td>
    </tr>
  {% endfor %}
  <tr>
      <td colspan="2"></td>
      <td>Итого:</td>
      <td>{{ cart.total_products }}</td>
      <td><strong>{{ cart.final_price }} $.</strong></td>
      <td><a href="{% url 'checkout' %}"><button class="btn btn-primaty">Перейти к оформлению</button> </a> </td>
  </tr>
  </tbody>
</table>
{% endif %}
{% endblock content%}

mainapp/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
            <li class="breadcrumb-item active">{{ category.name }}</li>
        </ol>
    </nav>
    <div class="row">
        {% for product in products %}
            {% if product.category.slug == category.slug %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
               <div style="width: 100%; height: 300px;.card img{ width: 100%;}">
                   <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a></div>
              <div class="card-body">
                <h4 class="card-title">
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} $</h5>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                    <button class="btn btn-danger">Добавить в корзину</button></a>
              </div>
            </div>
          </div>
            {% endif %}
        {% endfor %}
        </div>
{% endblock content %}

mainapp/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 300px; margin-top: 180px">
    <div class="col-md-6 offset-md-3">
        <h3 class="text-center">Авторизация</h3>
        <hr>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Войти">
        </form>
    </div>
</div>
{% endblock content %}

mainapp/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mt-3 mb-3">Заказы пользователя {{ request.user.username }}</h3>

{% if not orders.count %}
    <div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px;">
        <h3>У вас еще нет заказов. <a href="{% url 'base' %}">Начните делать покупки</a> </h3>
    </div>
{% else %}

    <div class="col-md-12" style="margin-bottom: 250px; margin-top: 250px;">
        <table class="table">
            <thead>
                <th scope="col">Номер</th>
                <th scope="col">Статус</th>
                <th scope="col">Сумма</th>
                <th scope="col">Товар</th>
                <th scope="col">Дополнительно</th>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.cart.final_price }} $.</td>
                        <td>
                            <ul>
                                {% for item in order.cart.products.all %}

                                    <li>{{ item.product.title }} x {{ item.qty }}</li>

                                {% endfor %}
                            </ul>
                        </td>
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">Дополнительно</button>

                        <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                                    <span aria-hidden="true">&times;</span>
                                </div>
                              <div class="modal-body">
                                  <h4 class="text-center">Товар</h4>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">Наимование</th>
                                                <th scope="col">Изображение</th>
                                                <th scope="col">Цена</th>
                                                <th scope="col">Кол-во</th>
                                                <th scope="col">Общая цена</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in order.cart.products.all %}
                                                <tr>
                                                    <th scope="row">{{ item.product.title }}</th>
                                                    <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"> </td>
                                                    <td><strong>{{ item.product.price }}</strong> $.</td>
                                                    <td>{{ item.qty }}</td>
                                                    <td>{{ item.final_price }} $.</td>
                                                </tr>
                                            {% endfor %}
                                                <tr>
                                                    <td colspan="2"></td>
                                                    <td>Итого:</td>
                                                    <td>{{ order.cart.total_products }}</td>
                                                    <td><strong>{{ order.cart.final_price }}</strong> $.</td>
                                                </tr>
                                        </tbody>
                                    </table>
                                        <hr>
                                        <h4 class="text-center">Дополнительная информация</h4>
                                        <p>Имя: <strong>{{ order.first_name }}</strong></p>
                                        <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                                        <p>Телефон: <strong>{{ order.phone }}</strong></p>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                              </div>
                            </div>
                          </div>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
{% endblock %}